version: '3'

services:
    dogecoin-core:
        build: .
        volumes:
            - ./data:/home/dogecoin/.dogecoin
            - ./dogecoin.conf:/home/dogecoin/.dogecoin/dogecoin.conf
        ports:
            - 22555:22555
        command:
            -printtoconsole
        